/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ActorPage {
  schema_version: "actor_page/1";
  world_id: string;
  viewer_id: string;
  actor: {
    id: string;
    perceived_name: string | null;
    perceived_role: string | null;
    current_synthesis: string | null;
    last_known_status: string | null;
    known_artifacts: {
      [k: string]: unknown;
    }[];
    inline_links: {
      [k: string]: unknown;
    }[];
    collected_knowledge_groups: {
      group_key: string;
      group_label: string | null;
      items: {
        perception_id: string;
        content: string;
        epistemic_type: string;
        occurred_at_tick: number;
        display_label: string | null;
        confidence: number;
        decay: {
          [k: string]: unknown;
        };
        source: {
          [k: string]: unknown;
        };
      }[];
    }[];
  };
}
